AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sam Template for CICD lambda pipeline
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::013058700034:role/service-role/index-photos-role-f2ai3pto'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
  Bucket1:
    Type: 'AWS::S3::Bucket'
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 1028
      Timeout: 60
      Role: 'arn:aws:iam::013058700034:role/service-role/search-photos-role-wg0h41ve'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /search
            Method: GET